### PR TITLE
[RETINA-309] Fixing transfer for reguler user

### LINKED ISSUE #309: Standard Users Cannot transfer their tools

### PR DESCRIPTION
**Pull request by Jbcampbe**
Closes #309

### CODE REVIEW

File: src/routes/tools.vue [hunk 1]
```diff
@@ -503,6 +537,9 @@ export default {
     moveToSelectingState () {
       this.$store.commit('setShowOnlySelectedTools', false)
       this.$store.commit('updateTransferStatus', this.states.SELECTING)
+      if (!this.isAdmin) {
+        this.clearSearchFilters()
```
Comment (Jbcampbe) [inline src/routes/tools.vue]: the user could have filters set that don't make sense (like users other than themselves)

File: src/routes/tools.vue [hunk 2]
```diff
@@ -418,6 +443,10 @@ export default {
       return this.getAllUser || []
     },
 
+    locationIds () {
+      return this.locations.map(location => location.id)
```
Comment (ekraihan) [inline src/routes/tools.vue]: This will call the getAllLocation endpoint?

File: src/routes/tools.vue [hunk 3]
```diff
@@ -7,7 +7,9 @@
         :update-tags="updateFilters"
         :disable-user-search="isNonAdminTransfer">
       </tool-search-input>
-      <nfc-scan :on-scan="onScan"></nfc-scan>
+      <!-- <nfc-scan :on-scan="onScan"></nfc-scan> -->
```
[the remark this answers is not in the document]
Comment (Jbcampbe) [reply src/routes/tools.vue]: nada. thanks
