### PR TITLE
[RETINA-241] Convert out of service to beyond reapir and lost/stolen

### LINKED ISSUE #241: Change Out of Service Statuses
Create Out of Service statuses:
  - Lost/Stolen
  - Broken

### PR DESCRIPTION
**Pull request by Jbcampbe**
Closes #241

### CODE REVIEW

File: src/routes/new-tool.vue [hunk 1]
```diff
@@ -340,8 +340,12 @@ export default {
           id: Statuses.MAINTENANCE
         },
         {
-          name: 'Out of Service',
-          id: Statuses.OUT_OF_SERVICE
+          name: 'Beyond Repair',
```
Comment (ekraihan) [inline src/routes/new-tool.vue]: Jsut wondering, should you be able to make a new tool that is out of service?

Comment (Jbcampbe) [reply src/routes/new-tool.vue]: no probably not cuz it would never show up and would have no history. good point : )
